"""
E2E test for injecting messages via POST /threads/{thread_id}/state

This test verifies that we can inject arbitrary messages (including AI messages)
into a thread's state without the agent actually generating them.
"""

import pytest

from tests.e2e._utils import elog, get_e2e_client


@pytest.mark.e2e
@pytest.mark.asyncio
async def test_inject_ai_message_via_state():
    """
    Test injecting an AI message into thread state without running the agent.
    """
    client = get_e2e_client()

    # 1. Create a thread with graph_id in metadata (required for state updates)
    thread = await client.threads.create(
        metadata={"graph_id": "ava"}
    )
    elog("Threads.create response", thread)
    assert "thread_id" in thread
    thread_id = thread["thread_id"]

    # 2. Get current state before injection (should be empty or minimal)
    state_before = await client.threads.get_state(thread_id=thread_id)
    elog("State before injection", state_before)
    messages_before = state_before.get("values", {}).get("messages", [])
    initial_message_count = len(messages_before)
    elog(f"Initial message count: {initial_message_count}", None)

    # 3. Inject a fake AI message using POST /threads/{thread_id}/state
    # This message was NOT generated by the agent
    fake_ai_message = {
        "type": "ai",  # Using LangChain format (not Agent Protocol format)
        "content": "This is a fake AI message injected via POST /state!",
        "id": "injected_msg_001",
    }

    elog("Injecting fake AI message", fake_ai_message)

    # Update state with the new message
    # Note: We're using LangGraph's internal format here
    # IMPORTANT: Initialize state fields to prevent KeyError if tools are called
    update_response = await client.threads.update_state(
        thread_id=thread_id,
        values={
            "messages": [fake_ai_message],
            # Initialize AVA state fields
            "hotelCursor": None,
            "roomCursor": None,
            "hotelToken": None,
            "hotelSearchKey": None,
            "roomSearchKey": None,
            "hotelParams": None,
            "roomParams": None,
            "location": None,
            "structured_response": None,
        },
    )
    elog("Update state response", update_response)
    assert "checkpoint" in update_response
    new_checkpoint_id = update_response["checkpoint"]["checkpoint_id"]
    elog(f"New checkpoint created: {new_checkpoint_id}", None)

    # 4. Verify the injected message appears in state
    state_after = await client.threads.get_state(thread_id=thread_id)
    elog("State after injection", state_after)
    messages_after = state_after.get("values", {}).get("messages", [])
    final_message_count = len(messages_after)

    elog(f"Final message count: {final_message_count}", None)
    assert final_message_count > initial_message_count, (
        "Message count should increase after injection"
    )

    # Find our injected message
    injected_message_found = any(
        msg.get("id") == "injected_msg_001" and msg.get("type") == "ai"
        for msg in messages_after
    )
    assert injected_message_found, "Injected AI message should be in state"

    # Verify the content
    injected_msg = next(
        msg for msg in messages_after if msg.get("id") == "injected_msg_001"
    )
    assert "fake AI message injected" in injected_msg["content"]

    elog("✅ Successfully injected AI message via POST /state", None)


@pytest.mark.e2e
@pytest.mark.asyncio
async def test_agent_sees_injected_messages():
    """
    Test that the agent can see injected messages when it runs.
    This is the critical test for the voice relay use case.
    """
    client = get_e2e_client()

    # 1. Create assistant
    assistant = await client.assistants.create(
        graph_id="ava",
        config={"tags": ["injection-visibility-test"]},
        if_exists="do_nothing",
    )
    elog("Assistant.create response", assistant)

    # 2. Create thread with graph_id
    thread = await client.threads.create(
        metadata={"graph_id": "ava"}
    )
    elog("Threads.create response", thread)
    thread_id = thread["thread_id"]

    # 3. Inject relay server messages BEFORE any run (real hotel booking example)
    hotel_context = {
        "type": "ai",
        "content": (
            "The hotel is JW Marriott Miami, a 5-star Hotel located in Miami, FL. "
            "Description: This 5-star luxury hotel, located 8.5 miles from Miami International "
            "Airport, offers an outdoor swimming pool and a 24-hour fitness center. A "
            "flat-screen TV and mini-bar are included with each room. A well-equipped gym is "
            "offered for guests that like to keep fit and free WiFi is available in public areas. "
            "Check-in: 16:00, Check-out: 12:00. "
            "Key amenities: ATM Bank Machine, Business Center, High Speed Internet, Bar/Lounge, "
            "Dry Cleaning/Valet Laundry Services, Gift Shop, Laundry Facility, Luggage Storage, "
            "Restaurant, Valet Parking. "
            "Hotel phone: 305-329-3500."
        ),
        "id": "relay_hotel_context_001",
    }
    relay_greeting = {
        "type": "ai",
        "content": (
            "Hi! I'm Ava from reservationsportal.com. I see you're looking to book a stay at JW "
            "Marriott Miami from December 1st to 5th for 2 adults. How can I help finalize your "
            "reservation?"
        ),
        "id": "relay_greeting_001",
    }

    elog("Injecting relay server messages (hotel context)", [hotel_context, relay_greeting])

    # IMPORTANT: Initialize ALL state fields to prevent KeyError when tools are called
    # The AVA graph expects these fields to exist, even if they're None
    state_values = {
        "messages": [hotel_context, relay_greeting],
        # Tool-related state fields (required for hotel search tools)
        "hotelCursor": None,
        "roomCursor": None,
        "hotelToken": None,
        "hotelSearchKey": None,
        "roomSearchKey": None,
        "hotelParams": None,
        "roomParams": None,
        "location": None,
        "structured_response": None,
    }

    update_response = await client.threads.update_state(
        thread_id=thread_id,
        values=state_values,
    )
    elog("Update state response", update_response)

    # 4. Verify messages are in state
    state_after_injection = await client.threads.get_state(thread_id=thread_id)
    elog("State after injection", state_after_injection)
    messages_after = state_after_injection.get("values", {}).get("messages", [])
    assert len(messages_after) == 2, "Should have 2 injected messages"

    # 5. Now customer asks a question that references the injected hotel info
    # The agent MUST see the previous messages to answer correctly
    elog("Creating run with customer question about check-in time", None)
    run = await client.runs.create(
        thread_id=thread_id,
        assistant_id=assistant["assistant_id"],
        input={
            "messages": [
                {
                    "role": "human",
                    "content": "What time is check-in?"  # References injected hotel context
                }
            ]
        },
    )
    elog("Run created", run)

    # 6. Wait for run to complete
    elog("Waiting for run to complete...", None)
    final_state = await client.runs.join(thread_id, run["run_id"])
    elog("Run completed, final state", final_state)

    # 7. Check if agent's response shows it saw the injected messages
    # runs.join() returns messages at top level, not in values
    if "messages" in final_state:
        final_messages = final_state["messages"]
    else:
        final_messages = final_state.get("values", {}).get("messages", [])

    elog(f"Final message count: {len(final_messages)}", None)
    elog("All messages in thread", final_messages)

    # Should have: relay_greeting + relay_property + human_question + ai_response
    assert len(final_messages) >= 4, (
        f"Expected at least 4 messages (2 injected + human + ai), got {len(final_messages)}"
    )

    # Check if the AI's response references the hotel check-in time
    # (proving it saw the injected hotel context)
    ai_response = final_messages[-1]  # Last message should be AI's response
    assert ai_response.get("type") == "ai", "Last message should be from AI"

    response_content = ai_response.get("content", "").lower()
    # The AI should mention "16:00" or "4 pm" or "4pm" if it saw the injected hotel context
    has_checkin_info = (
        "16:00" in response_content
        or "4 pm" in response_content
        or "4pm" in response_content
        or "four pm" in response_content
    )

    elog("AI response content", response_content)
    elog(f"AI referenced check-in time: {has_checkin_info}", None)

    if has_checkin_info:
        elog("✅ Agent successfully saw and used injected hotel context!", None)
    else:
        elog("❌ Agent may not have seen injected hotel context", None)
        elog("This means message injection doesn't work for the voice relay use case", None)

    assert has_checkin_info, (
        "Agent should have seen the injected hotel context and mentioned check-in time (16:00/4 PM)"
    )


@pytest.mark.e2e
@pytest.mark.asyncio
async def test_inject_multiple_messages():
    """
    Test injecting multiple messages at once.
    """
    client = get_e2e_client()

    # 1. Create thread with graph_id
    thread = await client.threads.create(
        metadata={"graph_id": "ava"}
    )
    thread_id = thread["thread_id"]

    # 2. Inject multiple messages at once
    fake_messages = [
        {
            "type": "human",
            "content": "Injected human message",
            "id": "injected_human_001",
        },
        {
            "type": "ai",
            "content": "Injected AI response",
            "id": "injected_ai_001",
        },
    ]

    elog("Injecting multiple messages", fake_messages)
    update_response = await client.threads.update_state(
        thread_id=thread_id,
        values={
            "messages": fake_messages,
            # Initialize AVA state fields
            "hotelCursor": None,
            "roomCursor": None,
            "hotelToken": None,
            "hotelSearchKey": None,
            "roomSearchKey": None,
            "hotelParams": None,
            "roomParams": None,
            "location": None,
            "structured_response": None,
        },
    )
    assert "checkpoint" in update_response

    # 3. Verify both messages appear
    state = await client.threads.get_state(thread_id=thread_id)
    messages = state.get("values", {}).get("messages", [])

    human_found = any(msg.get("id") == "injected_human_001" for msg in messages)
    ai_found = any(msg.get("id") == "injected_ai_001" for msg in messages)

    assert human_found, "Injected human message should be in state"
    assert ai_found, "Injected AI message should be in state"

    elog("✅ Successfully injected multiple messages", None)
