"""Add metadata for assistant table and cascade del for required foreign keys

Revision ID: aee821a02fc8
Revises: 76dfdbe90d2b
Create Date: 2025-09-13 21:35:35.407522

"""

import os

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# Keep migrations compatible with prefixed tables.
_PREFIX = os.getenv("AEGRA_TABLE_PREFIX", "")


def _tn(name: str) -> str:
    return f"{_PREFIX}{name}"

# revision identifiers, used by Alembic.
revision = "aee821a02fc8"
down_revision = "76dfdbe90d2b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        _tn("assistant"),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    assistant_versions_table = _tn("assistant_versions")
    runs_table = _tn("runs")

    op.drop_constraint(
        f"{assistant_versions_table}_assistant_id_fkey",
        assistant_versions_table,
        type_="foreignkey",
    )
    op.create_foreign_key(
        f"{assistant_versions_table}_assistant_id_fkey",
        assistant_versions_table,
        _tn("assistant"),
        ["assistant_id"],
        ["assistant_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(f"{runs_table}_assistant_id_fkey", runs_table, type_="foreignkey")
    op.create_foreign_key(
        f"{runs_table}_assistant_id_fkey",
        runs_table,
        _tn("assistant"),
        ["assistant_id"],
        ["assistant_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    assistant_versions_table = _tn("assistant_versions")
    runs_table = _tn("runs")

    op.drop_constraint(f"{runs_table}_assistant_id_fkey", runs_table, type_="foreignkey")
    op.create_foreign_key(
        f"{runs_table}_assistant_id_fkey",
        runs_table,
        _tn("assistant"),
        ["assistant_id"],
        ["assistant_id"],
    )
    op.drop_constraint(
        f"{assistant_versions_table}_assistant_id_fkey",
        assistant_versions_table,
        type_="foreignkey",
    )
    op.create_foreign_key(
        f"{assistant_versions_table}_assistant_id_fkey",
        assistant_versions_table,
        _tn("assistant"),
        ["assistant_id"],
        ["assistant_id"],
    )
    op.drop_column(_tn("assistant"), "metadata")
    # ### end Alembic commands ###
