"""Add context

Revision ID: 5931cd77e93b
Revises: 7b79bfd12626
Create Date: 2025-08-30 16:17:58.752557

"""

import os

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# Keep migrations compatible with prefixed tables.
_PREFIX = os.getenv("AEGRA_TABLE_PREFIX", "")


def _tn(name: str) -> str:
    return f"{_PREFIX}{name}"

# revision identifiers, used by Alembic.
revision = "5931cd77e93b"
down_revision = "7b79bfd12626"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        _tn("assistant"),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        _tn("runs"),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(_tn("runs"), "context")
    op.drop_column(_tn("assistant"), "context")
    # ### end Alembic commands ###
