"""Add activity log table for student tracking

Revision ID: c22c266e4542
Revises: aee821a02fc8
Create Date: 2025-10-29 22:41:57.113033

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "c22c266e4542"
down_revision = "aee821a02fc8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_log",
        sa.Column(
            "activity_id",
            sa.Text(),
            server_default=sa.text("uuid_generate_v4()::text"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("assistant_id", sa.Text(), nullable=True),
        sa.Column("thread_id", sa.Text(), nullable=True),
        sa.Column("run_id", sa.Text(), nullable=True),
        sa.Column("action_type", sa.Text(), nullable=False),
        sa.Column(
            "action_status",
            sa.Text(),
            server_default=sa.text("'success'"),
            nullable=False,
        ),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("activity_id"),
    )
    op.create_index(
        "idx_activity_log_action_type", "activity_log", ["action_type"], unique=False
    )
    op.create_index(
        "idx_activity_log_assistant", "activity_log", ["assistant_id"], unique=False
    )
    op.create_index(
        "idx_activity_log_created", "activity_log", ["created_at"], unique=False
    )
    op.create_index(
        "idx_activity_log_thread", "activity_log", ["thread_id"], unique=False
    )
    op.create_index("idx_activity_log_user", "activity_log", ["user_id"], unique=False)
    op.create_index(
        "idx_activity_log_user_created",
        "activity_log",
        ["user_id", "created_at"],
        unique=False,
    )
    # Drop old LangGraph checkpoint tables if they exist
    op.execute("DROP INDEX IF EXISTS checkpoints_thread_id_idx")
    op.execute("DROP TABLE IF EXISTS checkpoints CASCADE")
    op.execute("DROP TABLE IF EXISTS checkpoint_migrations CASCADE")
    op.execute("DROP TABLE IF EXISTS store_migrations CASCADE")
    op.execute("DROP INDEX IF EXISTS checkpoint_writes_thread_id_idx")
    op.execute("DROP TABLE IF EXISTS checkpoint_writes CASCADE")
    op.execute("DROP INDEX IF EXISTS idx_store_expires_at")
    op.execute("DROP INDEX IF EXISTS store_prefix_idx")
    op.execute("DROP TABLE IF EXISTS store CASCADE")
    op.execute("DROP INDEX IF EXISTS checkpoint_blobs_thread_id_idx")
    op.execute("DROP TABLE IF EXISTS checkpoint_blobs CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checkpoint_blobs",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("channel", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("version", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("blob", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "thread_id",
            "checkpoint_ns",
            "channel",
            "version",
            name=op.f("checkpoint_blobs_pkey"),
        ),
    )
    op.create_index(
        op.f("checkpoint_blobs_thread_id_idx"),
        "checkpoint_blobs",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "store",
        sa.Column("prefix", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("key", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "value",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("ttl_minutes", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("prefix", "key", name=op.f("store_pkey")),
    )
    op.create_index(
        op.f("store_prefix_idx"),
        "store",
        ["prefix"],
        unique=False,
        postgresql_ops={"prefix": "text_pattern_ops"},
    )
    op.create_index(
        op.f("idx_store_expires_at"),
        "store",
        ["expires_at"],
        unique=False,
        postgresql_where="(expires_at IS NOT NULL)",
    )
    op.create_table(
        "checkpoint_writes",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("checkpoint_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("idx", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("channel", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("blob", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.Column(
            "task_path",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "thread_id",
            "checkpoint_ns",
            "checkpoint_id",
            "task_id",
            "idx",
            name=op.f("checkpoint_writes_pkey"),
        ),
    )
    op.create_index(
        op.f("checkpoint_writes_thread_id_idx"),
        "checkpoint_writes",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "store_migrations",
        sa.Column("v", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("v", name=op.f("store_migrations_pkey")),
    )
    op.create_table(
        "checkpoint_migrations",
        sa.Column("v", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("v", name=op.f("checkpoint_migrations_pkey")),
    )
    op.create_table(
        "checkpoints",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("checkpoint_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "parent_checkpoint_id", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "checkpoint",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "thread_id", "checkpoint_ns", "checkpoint_id", name=op.f("checkpoints_pkey")
        ),
    )
    op.create_index(
        op.f("checkpoints_thread_id_idx"), "checkpoints", ["thread_id"], unique=False
    )
    op.drop_index("idx_activity_log_user_created", table_name="activity_log")
    op.drop_index("idx_activity_log_user", table_name="activity_log")
    op.drop_index("idx_activity_log_thread", table_name="activity_log")
    op.drop_index("idx_activity_log_created", table_name="activity_log")
    op.drop_index("idx_activity_log_assistant", table_name="activity_log")
    op.drop_index("idx_activity_log_action_type", table_name="activity_log")
    op.drop_table("activity_log")
    # ### end Alembic commands ###
